# -*- coding: utf-8 -*-
"""atm_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJSfZ4CsCiB-A9lCM_OlhvSIQXb8r7-Z
"""

# Python ATM Simulator
def atm():
  balance = 2000        # Initial balance in the account
  pin = 1973            # ATM PIN (fixed for this simulator)
  attempts = 3          # Number of attempts allowed to enter the correct PIN

  print("===================== Welcome to Python ATM Simulator =========================")

  # Loop for PIN entry, runs until attempts run out
  while attempts > 0:
    entered_pin = int(input("Enter your ATM Pin :"))  # User enters PIN

    # If entered PIN matches the correct PIN
    if entered_pin == pin:
      print("Access granted")

      # ATM menu loop
      while True:
        print(" ATM Menu ")
        print("1. Check balance")
        print("2. Deposit money")
        print("3. Withdraw money")
        print("4. Exit")

        try:
          choice = int(input("Choose between the following options: "))
        except ValueError:
          print("Invalid input! Please enter between 1-4: ")
          print("-" * 70)
          continue  # Go back to the menu

        # Option 1: Check balance
        if choice == 1:
          print(f"Your current balance is : {balance}")
          print("-" * 70)

        # Option 2: Deposit money
        elif choice == 2:
          try:
            amount = int(input("Enter your Deposit amount: "))
            if amount > 0:
              balance += amount
              print(f"Your Deposit amount is : {amount} and your new balance is : {balance}")
            else:
              print("Invalid amount!")
          except ValueError:
            print("Invalid Deposit amount! Please enter a number")
          print("-" * 70)

        # Option 3: Withdraw money
        elif choice == 3:
          try:
            amount = int(input("Please enter your Withdraw amount :"))
            if amount > 0:
              if amount <= balance:
                balance -= amount
                print(f"Your Withdraw amount is : {amount} and your new balance is : {balance}")
              else:
                print("Insufficient balance")
          except ValueError:
            print("Invalid withdraw amount! Please enter a number:")
          print("-" * 70)

        # Option 4: Exit
        elif choice == 4:
          print("Thank you for using Python ATM Simulator")
          return   # Exit the ATM function

    # If entered PIN is incorrect
    else:
      attempts -= 1
      print(f"Incorrect PIN! Attempts left : {attempts}")
      if attempts == 0:   # No attempts left → card blocked
        print("Too many attempts! Your ATM card is blocked")
        return

# Call the ATM function to run the program
atm()